---
- hosts: localhost
  connection: local

  tasks:
    - name: Install python-psutil package
      become: true
      apt:
        name: python-psutil

    - name: Copy wallpaper file
      become: true
      copy:
        src: files/concrete_monk.jpg
        dest: "/home/{{ansible_env.SUDO_USER}}/.wallpaper.jpg"
        owner: "{{ansible_env.SUDO_USER}}"
        group: "{{ansible_env.SUDO_USER}}"
        mode: 500

    - name: tricky trick
      shell: "a=\"'file:///home/\"; b=\"/.wallpaper.jpg'\"; echo ${a}{{ansible_env.SUDO_USER}}${b}"
      register: result

    - name: Print return information from the previous task
      ansible.builtin.debug:
        msg: "result: {{result}}"

    - name: Set GNOME Wallpaper
      become_user: "{{ansible_env.SUDO_USER}}"
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "{{result.stdout}}"
        state: present
