---
- hosts: localhost
  connection: local

  tasks:
    - name: Install python-psutil package
      become: true
      apt:
        name: python-psutil

    - name: Copy wallpaper file
      become: true
      copy:
        src: files/concrete_monk.jpg
        dest: "/usr/share/backgrounds/ansible-wallpaper.jpg"

    - name: Set GNOME Wallpaper
      become_user: "{{ansible_env.SUDO_USER}}"
      dconf:
        key: "/org/gnome/desktop/background/picture-uri"
        value: "'file:///usr/share/backgrounds/ansible-wallpaper.jpg'"
